rows <- sample(seq(1000, 2000), 1)
disc_vars <- sample(seq(2, 8), 1)
cont_vars <- sample(seq(3, 8), 1)

dt <- gen_marg_joint_data(n_obs = rows,
                          n_disc = disc_vars,
                          n_cont = cont_vars,
                          n_lvls = 3,
                          p_outs = 0.05,
                          jp_outs = 0.2,
                          assoc_target = 1,
                          assoc_vars = c(1,2),
                          assoc_type="linear",
                          seed_num = 1)
test_that("Correct number of output dimensions.", {
  expect_equal(dim(dt), c(rows, (disc_vars+cont_vars+1)))
})

test_that("Correct type of output variables.", {
  expect_equal(all(sapply(dt[,c(1:disc_vars)], class)=="factor"), TRUE)
  expect_equal(all(sapply(dt[,c((disc_vars+1):(disc_vars+cont_vars))], class)=="numeric"), TRUE)
})

dt <- gen_marg_joint_data(n_obs = rows,
                          n_disc = disc_vars,
                          n_cont = cont_vars,
                          n_lvls = 3,
                          p_outs = 0.10,
                          jp_outs = 0,
                          assoc_target = 1,
                          assoc_vars = c(1,2),
                          assoc_type="linear",
                          seed_num = 1)
test_that("Correct output labels for no joint outliers.", {
  expect_equal(length(which(dt[, (disc_vars+cont_vars+1)] == 3)), 0)
  expect_equal(length(which(dt[, (disc_vars+cont_vars+1)] %in% c(0, 1, 2))), rows)
})

dt <- gen_marg_joint_data(n_obs = rows,
                          n_disc = disc_vars,
                          n_cont = cont_vars,
                          n_lvls = 3,
                          p_outs = 0.10,
                          jp_outs = 1,
                          assoc_target = 1,
                          assoc_vars = c(1,2),
                          assoc_type="linear",
                          seed_num = 1)
test_that("Correct output labels for no marginal outliers.", {
  expect_equal(length(which(dt[, (disc_vars+cont_vars+1)] %in% c(1, 2))), 0)
  expect_equal(length(which(dt[, (disc_vars+cont_vars+1)] %in% c(0, 3))), rows)
})

dt <- gen_marg_joint_data(n_obs = rows,
                          n_disc = disc_vars,
                          n_cont = cont_vars,
                          n_lvls = 3,
                          p_outs = 0,
                          jp_outs = 0,
                          assoc_target = 1,
                          assoc_vars = c(1,2),
                          assoc_type="linear",
                          seed_num = 1)
test_that("Correct output labels for no outliers.", {
  expect_equal(length(which(dt[, (disc_vars+cont_vars+1)] %in% c(1, 2, 3))), 0)
  expect_equal(length(which(dt[, (disc_vars+cont_vars+1)] == 0)), rows)
})

test_that("Incorrect input variable values error messages.", {
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 0.1),
               "Seed number should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 2.1),
               "Seed number should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 0),
               "Seed number should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = -26),
               "Seed number should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = 1.4,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of discrete/continuous variables should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = 0,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of discrete/continuous variables should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = -5,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of discrete/continuous variables should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = 8.4,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of discrete/continuous variables should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = 0,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of discrete/continuous variables should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = -2,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of discrete/continuous variables should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.21,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Proportion of outliers should be at most 0.2 and at least 0.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = -0.01,
                                         jp_outs = 0.2,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Proportion of outliers should be at most 0.2 and at least 0.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = -0.01,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Proportion of joint outliers should be between 0 and 1.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 1.01,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Proportion of joint outliers should be between 0 and 1.")
  expect_error(dt <- gen_marg_joint_data(n_obs = -1*rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of observations should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows + 0.1,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of observations should be a positive integer.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3.1,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of levels should be an integer at least equal to 2 and at most equal to n_obs.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = -3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of levels should be an integer at least equal to 2 and at most equal to n_obs.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 1,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of levels should be an integer at least equal to 2 and at most equal to n_obs.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = rows + 1,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Number of levels should be an integer at least equal to 2 and at most equal to n_obs.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = rep(3, (disc_vars + 1)),
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = 1,
                                         assoc_vars = c(1,2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Vector of number of levels should either be of unit length or of length equal to n_disc.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = (disc_vars + 1),
                                         assoc_vars = c(1, 2),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Incorrect column index for association target variable.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 1),
                                         assoc_vars = list(c(1, 2), c(1, 2)),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Cannot define 2 associations with the same target.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2), c(1, 2)),
                                         assoc_type="anything else",
                                         seed_num = 1),
               "Only association types 'linear', 'product' and 'quotient' are supported.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2), c(1, 2)),
                                         assoc_type=rep("linear", 3),
                                         seed_num = 1),
               "Length of association type should be either 1 or equal to the length of association targets.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = 1,
                                         assoc_vars = list(c(1, 2), c(1, 2)),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Length of association targets should be equal to length of list of association variables.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 1), c(1, 2)),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Association variables should be unique positive integers, at most equal to n_cont.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, -0.1), c(1, 2)),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Association variables should be unique positive integers, at most equal to n_cont.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 1.1), c(1, 2)),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Association variables should be unique positive integers, at most equal to n_cont.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 0), c(1, 2)),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Association variables should be unique positive integers, at most equal to n_cont.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2), c(1, cont_vars+1)),
                                         assoc_type="linear",
                                         seed_num = 1),
               "Association variables should be unique positive integers, at most equal to n_cont.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2), c(1, 2)),
                                         assoc_type=c("linear", "product"),
                                         seed_num = 1),
               "Cannot have linear and product/quotient associations for sets of variables with common elements.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2), c(1, 3)),
                                         assoc_type=c("linear", "product"),
                                         seed_num = 1),
               "Cannot have linear and product/quotient associations for sets of variables with common elements.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2), c(1, 2)),
                                         assoc_type=c("linear", "quotient"),
                                         seed_num = 1),
               "Cannot have linear and product/quotient associations for sets of variables with common elements.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2), c(1, 3)),
                                         assoc_type=c("linear", "quotient"),
                                         seed_num = 1),
               "Cannot have linear and product/quotient associations for sets of variables with common elements.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2, 3), c(1, 3)),
                                         assoc_type=c("linear", "quotient"),
                                         seed_num = 1),
               "Cannot have linear and product/quotient associations for sets of variables with common elements.")
  expect_error(dt <- gen_marg_joint_data(n_obs = rows,
                                         n_disc = disc_vars,
                                         n_cont = cont_vars,
                                         n_lvls = 3,
                                         p_outs = 0.05,
                                         jp_outs = 0.20,
                                         assoc_target = c(1, 2),
                                         assoc_vars = list(c(1, 2, 3), c(1, 3)),
                                         assoc_type=c("linear", "product"),
                                         seed_num = 1),
               "Cannot have linear and product/quotient associations for sets of variables with common elements.")
})
